trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'jeancalistro/alunos-api-dev'
      command: 'buildAndPush'
      Dockerfile: './Dockerfile'
      buildContext: './'
      tags: |
        $(Build.BuildId)
        latest
        