services:
  db:
    image: postgres
    container_name: ${POSTGRES_DOMAIN_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - network-api
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: api
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DOMAIN_NAME},${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - '${API_PORT}:8000'
    networks:
      - network-api
networks:
  network-api:
    driver: bridge
