name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t jeancalistro/alunos-api:${{ github.run_id }}
      - name: push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push jeancalistro/alunos-api:${{ github.run_id }}
